# Generated by Django 4.1.7 on 2023-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=30)),
                ('E_mail', models.EmailField(max_length=20)),
                ('Phon_number', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=30)),
                ('NID_Number', models.PositiveIntegerField()),
                ('Image', models.ImageField(upload_to='prog_pic')),
                ('Addres', models.TextField(max_length=50)),
            ],
        ),
    ]
